version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      # For Linux, use 172.17.0.1 as the Docker host gateway
      - MONGODB_URI=mongodb://local_mongo:27017/church-app
      # - MONGODB_URI=mongodb://admin:secret@45.9.190.68:27017/church-app?authSource=admin



    
      - NODE_ENV=production
    restart: unless-stopped
    


##Server                                                  docker-compose.yml                                                                                              
# version: "3.8"

# networks:
#   haunted_net:
#     external: true

# services:
#   app:
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       - MONGODB_URI=mongodb://local_mongo:27017/church-app
#       - NODE_ENV=production
#     restart: unless-stopped
#     networks:
#       - haunted_net
