version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      # For Linux, use 172.17.0.1 as the Docker host gateway
      - MONGODB_URI=mongodb://admin:secret@172.17.0.1:27018/ubh-db?authSource=admin
      - NODE_ENV=production
    restart: unless-stopped

